<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DotNetTargetFx)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Contracts</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="src\" />
    </ItemGroup>

</Project>
